---
name: CMake on multiple platforms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Check source code formatting
      run: |
        for i in $(find src -name '*.c' -o -name '*.h') $(find src -name '*.cc'); do
          if clang-format --style=file:.clang-format -n $i 2>&1 | grep -q .; then
            clang-format --style=file:.clang-format -n $i
            exit 1
          fi
        done

  cmake-format:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Check CMake formatting
      run: |
        pip install cmakelang
        cmake-format --check $(find src/ -name CMakeLists.txt)
        cmake-format --check CMakeLists.txt
        cmake-format --check $(find tests/ -name CMakeLists.txt)
        cmake-format --check $(find cmake/ -type f)

  build:
    needs: [format, cmake-format]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix: &matrix
        os: [ubuntu-24.04, windows-2025]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
        - os: windows-2025
          c_compiler: cl
          cpp_compiler: cl
        - os: ubuntu-24.04
          c_compiler: gcc
          cpp_compiler: g++
        - os: ubuntu-24.04
          c_compiler: clang
          cpp_compiler: clang++
        exclude:
        - os: windows-2025
          c_compiler: gcc
        - os: windows-2025
          c_compiler: clang
        - os: ubuntu-24.04
          c_compiler: cl

    steps:
    - uses: actions/checkout@v5

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -S ${{ github.workspace }}

    - name: Compile project
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Archive build directory
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact-${{ matrix.os }}-${{ matrix.c_compiler }}-${{ matrix.build_type }}
        path: ${{ steps.strings.outputs.build-output-dir }}
        retention-days: 1

  test:
    needs: [build]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix: *matrix

    steps:
    - uses: actions/checkout@v5

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Download build directory
      uses: actions/download-artifact@v4
      with:
        name: build-artifact-${{ matrix.os }}-${{ matrix.c_compiler }}-${{ matrix.build_type }}
        path: ${{ steps.strings.outputs.build-output-dir }}

    - name: Fix permissions for executables
      if: runner.os != 'Windows'
      run: >
        find ${{ steps.strings.outputs.build-output-dir }} -type f \( -name '*_test' -o -name stegtool \) -exec chmod +x {} \;

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

  lint:
    needs: [build]
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Download build directory
      uses: actions/download-artifact@v4
      with:
        name: build-artifact-ubuntu-24.04-gcc-Release
        path: ${{ steps.strings.outputs.build-output-dir }}

    - name: Copy compile_commands.json database
      run: |
        cp ${{ steps.strings.outputs.build-output-dir }}/compile_commands.json .

    - name: Run clang-tidy
      run: |
        clang-tidy --config-file=.clang-tidy $(find src -name '*.c' -o -name '*.h') $(find tests -name '*.cc')
